package io.github.t3m8ch.quizbot.constants

const val START_QUIZ = "START_QUIZ"
const val PREVIOUS_QUIZ_PAGE = "PREVIOUS_QUIZ_PAGE"
const val CURRENT_QUIZ_PAGE = "CURRENT_QUIZ_PAGE"
const val NEXT_QUIZ_PAGE = "NEXT_QUIZ_PAGE"
const val QUIZZES_PAGE_INDEX = "QUIZZES_PAGE_INDEX"
const val QUIZZES_PAGINATOR_MESSAGE_ID = "QUIZZES_PAGINATOR_MESSAGE_ID"
const val CURRENT_QUIZ = "CURRENT_QUIZ"
const val CURRENT_QUESTION_INDEX = "CURRENT_QUESTION_INDEX"
